#! /usr/bin/env bash

set +x

rebuild_hyprland_hdmi_mutable() {
  home-manager switch --flake .#
}

rebuild() {
  sudo nixos-rebuild switch --flake .#thinkpad-x1
}

init() {
  echo "Creating directories..."

  mkdir -p $HOME/Pictures/
  cp imgs/

  mkdir -p $HOME/.config/nix
  cp home/nix.conf $HOME/.config/nix/nix.conf
}

case $1 in
  "init")
    init;;
  *)
    echo "wrong argument";;
esac