#! /usr/bin/env bash

set +x

rebuild_hm() {
  home-manager switch --flake .#
}

rebuild() {
  sudo nixos-rebuild switch --flake .#thinkpad-x1
}

init() {
  echo "Creating directories..."

  mkdir -p $HOME/Pictures/
  cp imgs/img19.jpg $HOME/Pictures/img19.jpg

  mkdir -p $HOME/.config/nix
  cp home/nix.conf $HOME/.config/nix/nix.conf
}

case $1 in
  "rebuild_hm")
    rebuild_hm;;
  "rebuild")
    rebuild;;
  "init")
    init;;
  *)
    echo "wrong argument";;
esac