#! /usr/bin/env bash

set +x

rebuild_hm() {
  home-manager switch --flake .#
}

rebuild() {
  if [ -z "$1" ]; then
    echo "no hostname"
    exit 1
  fi
  sudo nixos-rebuild switch --flake ".#$1"
}

init() {
  echo "creating directories..."

  mkdir -p "$HOME/Pictures/"
  cp imgs/img19.jpg "$HOME/Pictures/img19.jpg"

  mkdir -p "$HOME/.config/nix"
  cp system/misc/nix.conf "$HOME/.config/nix/nix.conf"
}

case $1 in
  "rebuild_hm")
    rebuild_hm;;
  "rebuild")
    rebuild "$2";;
  "init")
    init;;
  *)
    echo "wrong argument";;
esac
