name: Build NixOS and Home Manager

on:
  push:
    branches: [ main ]
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'system/**'
      - 'home/**'
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'system/**'
      - 'home/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check flake
        run: nix flake check

      - name: Build NixOS
        run: nix build .#nixosConfigurations.nix-usb.config.system.build.toplevel

      - name: Build Home Manager
        run: nix build .#homeConfigurations.hyprland.activationPackage
