creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - age1je530qzdymgghvezwefe4w7w08mqhtpq6svqetgfd4thgy6edpuqjfy6tv # personal
          - age1hkeqffhus894mrwrzyteyhes2mn67j55ekwensemhe2fpa0uwgrqfzgrcs # home
          - age1xx4vgacsyq3nuzh74jg5al3lxq7yscerfw3nwpmsgc8kpgjufeys6dwdnv # thinkpad
          - age1yzz8sjmvj33ndjavesh6ulylc9nk3xcf076mvvg4utxsdrpkxfpq6a0x5w # stockholm
          - age1wwngndk9jkleyauu05ufxj8dpuq6k2wja45r9x6futccc3ccz5cs5fs7g4 # nest
          - age1rn47uc6pyncdre9qgvt0cxsz9v4rutpxdef8t40cckd7fmxscqwskvwpy3 # almaty
