creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - age1je530qzdymgghvezwefe4w7w08mqhtpq6svqetgfd4thgy6edpuqjfy6tv # personal
          - age1hkeqffhus894mrwrzyteyhes2mn67j55ekwensemhe2fpa0uwgrqfzgrcs # home
          - age1xx4vgacsyq3nuzh74jg5al3lxq7yscerfw3nwpmsgc8kpgjufeys6dwdnv # thinkpad
          - age1gaa42h0t4tpun7tgr7xghn3pww3e89rdgvh4uhdfdwruger2x4jqt3lvam # london
          - age1yzz8sjmvj33ndjavesh6ulylc9nk3xcf076mvvg4utxsdrpkxfpq6a0x5w # stockholm
          - age1h8u8p86yu7s94hknyhhz7ldqwd4c367jz2rg05x93ml5u2zmhgvqvhpl9z # helsinki
          - age1w584le5gw030hjpdmxtf3g5hhxqs03can0tlcsupsxpqpqv4k35s5s0v5j # relay
          - age1redjzchky3k6nn94h50lzpzr0drp6j8vgua74tx82dxlereq595qyvhmjw # moscow
          - age1wwngndk9jkleyauu05ufxj8dpuq6k2wja45r9x6futccc3ccz5cs5fs7g4 # nest
